### ISSUE TITLE
pan/zoom in the julia_gui demo?

### ISSUE THREAD

**Issue by lobingera** [timholy/GtkUtilities.jl#1]
If i understand the setting in the demo correctly, this should enable 
- button1 rubberband select -> works
- ctrl+wheel zoom in and out -> works
- if zoomed in, wheel pans up and down, with shift left and right

But somehow i miss panning with mouse (pointer)?

**Comment by lobingera** [comment]
Now as i read the third time, there is no pan with mouse pointer ...

**Comment by timholy** [comment]
It's certainly something that could be added. What should the interface be---right-click/drag? Or ALT-click/drag? Something else?

**Comment by lobingera** [comment]
... needs to be configurable ...

button1 click drag for selection
button3 click drag for panning?
