### ISSUE TITLE
ERROR: Direction 3 not recognized

### ISSUE THREAD

**Issue by Keno** [timholy/GtkUtilities.jl#2]
Moving this over from https://github.com/timholy/ProfileView.jl/issues/43:

```
julia> FATAL ERROR: Gtk state corrupted by error thrown in a callback:
ERROR: Direction 3 not recognized
 in scrollpm at /Users/kfischer/.julia/v0.5/GtkUtilities/src/panzoom.jl:385
 in anonymous at /Users/kfischer/.julia/v0.5/GtkUtilities/src/panzoom.jl:354
 in mousescroll_cb at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:193
 in anonymous at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:2
 in g_sigatom at /Users/kfischer/.julia/v0.5/Gtk/src/GLib/signals.jl:166
 in gtk_main at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:1
```

This happens on a macbook with two-finger swipe.

**Comment by timholy** [comment]
Thanks for moving it. I'm not sure which sign to assign in [these lines](https://github.com/timholy/GtkUtilities.jl/blob/c7f39f381f28e6ab364299f1e34e22f99107d2de/src/panzoom.jl#L385-L387), and my KDE system only generates UP/DOWN events. Would be great if you could test.

**Comment by timholy** [comment]
With my system, I get left-right by scrolling the wheelmouse and holding down SHIFT. Obviously it would be better to do something directly with LEFT/RIGHT events, but I'm hesitant to develop it if I can't test...
