### ISSUE TITLE
New version to support Images.jl v0.22

### ISSUE THREAD

**Issue by Wikunia** [timholy/GtkUtilities.jl#32]
I've just realized that you've created a new release in February and changed the Project.toml afterwards to support v0.22 of Images.jl but haven't released a version since then.
Do you mind to release v1.0.4 for this? :wink:

**Comment by jonathanBieler** [comment]
Oups sorry, hopefully it should be merged shortly : https://github.com/JuliaRegistries/General/pull/20992
